"""
Final Analysis Report Models for CodeSlim.

Defines Pydantic models for bloat map entries, confidence tier classifications,
and the final complete CodeSlimReport object.
"""

from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field, computed_field

from codeslim.models.metrics import FileMetrics


class BloatMapEntry(BaseModel):
    """Specific code bloat area identified during analysis."""

    bloat_type: str = Field(description="Category of code bloat")
    severity: str = Field(description="Severity level: low, medium, high, critical")
    line_start: int = Field(ge=1, description="Starting line number")
    line_end: int = Field(ge=1, description="Ending line number")
    explanation: str = Field(description="Explanation of identified bloat")
    suggestion: str = Field(default="", description="Recommended action")


class ConfidenceTiers(BaseModel):
    """3-Tier confidence classification for optimization changes."""

    auto_safe: list[dict[str, Any]] = Field(default_factory=list, description="Tier 1: Safe automated changes")
    suggest: list[dict[str, Any]] = Field(
        default_factory=list, description="Tier 2: Recommended developer-reviewed changes"
    )
    flag_only: list[dict[str, Any]] = Field(
        default_factory=list, description="Tier 3: Structural changes requiring manual review"
    )


class CodeSlimReport(BaseModel):
    """Complete summary report generated by a CodeSlim analysis run."""

    file_path: str = Field(description="Analyzed file path")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        description="UTC timestamp of analysis completion",
    )
    duration_seconds: float = Field(default=0.0, ge=0.0, description="Pipeline execution duration")
    pipeline_version: str = Field(default="0.1.0", description="CodeSlim version")

    bloat_score: float = Field(default=0.0, ge=0.0, le=100.0, description="Overall bloat score (0-100)")
    original_lines: int = Field(default=0, ge=0, description="Original file line count")
    optimized_lines: int | None = Field(default=None, ge=0, description="Optimized line count")

    bloat_map: list[BloatMapEntry] = Field(default_factory=list, description="Detailed bloat map")
    hallucinated_packages: list[str] = Field(default_factory=list, description="Confirmed non-existent packages")

    optimized_code: str | None = Field(default=None, description="Minimized code output")
    diff: str | None = Field(default=None, description="Unified diff string")
    confidence_tiers: ConfidenceTiers = Field(
        default_factory=ConfidenceTiers, description="Tiered confidence categorization"
    )

    metrics: FileMetrics | None = Field(default=None, description="Raw static analysis metrics")
    errors: list[str] = Field(default_factory=list, description="Non-fatal execution errors")
    stages_completed: list[str] = Field(default_factory=list, description="Completed pipeline stages")

    @computed_field
    @property
    def file_name(self) -> str:
        """Extract filename from file_path."""
        return Path(self.file_path).name

    @computed_field
    @property
    def max_cc(self) -> int:
        """Maximum cyclomatic complexity across functions."""
        if not self.metrics or not self.metrics.functions:
            return 0
        return max(f.cyclomatic_complexity for f in self.metrics.functions)

    @computed_field
    @property
    def dead_code_count(self) -> int:
        """Total dead code items found."""
        if not self.metrics:
            return 0
        return len(self.metrics.dead_code)

    @computed_field
    @property
    def duplication_ratio(self) -> float:
        """Duplication ratio fraction."""
        if not self.metrics:
            return 0.0
        return self.metrics.duplication_ratio

    @computed_field
    @property
    def lines_saved(self) -> int:
        """Net reduction in lines of code."""
        if self.optimized_lines is None:
            return 0
        return max(0, self.original_lines - self.optimized_lines)

    @computed_field
    @property
    def reduction_percentage(self) -> float:
        """Percentage reduction in lines of code."""
        if self.original_lines == 0 or self.optimized_lines is None:
            return 0.0
        return round((self.lines_saved / self.original_lines) * 100.0, 1)

    @computed_field
    @property
    def bloat_grade(self) -> str:
        """Letter grade based on bloat score (A: <=20, B: <=40, C: <=60, D: <=80, F: >80)."""
        if self.bloat_score <= 20.0:
            return "A"
        if self.bloat_score <= 40.0:
            return "B"
        if self.bloat_score <= 60.0:
            return "C"
        if self.bloat_score <= 80.0:
            return "D"
        return "F"
